services:
  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_DB: pgboss
    ports:
      - "${DATABASE_HOST:-127.0.0.1}:${DATABASE_PORT:-5432}:5432"
    command:
      - "postgres"
      - "-c"
      - "config_file=/var/lib/postgresql/postgresql.conf"
    volumes:
      - ./pgdump:/var/lib/postgresql/pgdump
    container_name: pgboss
