services:
  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: "127.0.0.1"
      POSTGRES_DB: "pgboss"
    ports:
      - "127.0.0.1:5444:5432"
    command:
      - "postgres"
      - "-c"
      - "config_file=/var/lib/postgresql/postgresql.conf"
    container_name: "pgboss"
